#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BlurExample.Resource", IsApplication=true)]

namespace BlurExample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int black = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int blue = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int dialog_selected_top_bottom = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int dialog_selected_top_top = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int dialog_unselected_top_bottom = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int dialog_unselected_top_top = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int general_store_product_background = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int general_store_product_item_background = 2130968596;
			
			// aapt resource value: 0x7f040005
			public const int grey = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int grey_white = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int link_blue = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int product_sheet_dialog_background = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int product_sheet_dialog_line = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int product_sheet_dialog_suite = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int product_sheet_dialog_summary_background = 2130968585;
			
			// aapt resource value: 0x7f040010
			public const int search_dialog_section_bottom = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int search_dialog_section_top = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int settings_dialog_background = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int settings_text = 2130968594;
			
			// aapt resource value: 0x7f040000
			public const int transparent = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int capitale = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int country = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int decoration = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int dog_monkey = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int drawer_shadow_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drawer_shadow_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int food = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int garden = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int gear = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int golf = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int home = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_drawer_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_drawer_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int living = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mac = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int maison = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int motor = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int msr = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int planet = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int voiture = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int week = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int wired = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int blur_image = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int drawer_layout = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int framelayout = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int grid = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int left_drawer = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int issue_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int item_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
